# Generated by Django 2.1 on 2018-09-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amigos',
            new_name='Amigo',
        ),
    ]
