# Generated by Django 2.1 on 2018-09-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoApp', '0002_auto_20180910_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('salary', models.FloatField(max_length=100)),
            ],
        ),
    ]
