# Generated by Django 2.1 on 2018-09-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoApp', '0004_auto_20180921_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Pessoas'},
        ),
    ]
